lib/clients/AwsClient.py
lib/clients/AzureClient.py
lib/clients/BaseClient.py

This PR includes : 
- changes to tag snapshots and volumes for AWS backups.
Eg:
- changes to tag disks and snapshots for Azure backups.
Eg:

 Tagging of snapshots/volumes/disks for better tracking

---

lib/clients/BaseClient.py

-Parameterize the filesystem type for both format device (used for backups) and
mount device (used for restore)
-Filesystem type should not be defaulted to "ext4" since any service can request its own filesystem type from IaaS for Backup and Restore

Parameterize the filesystem type

---

lib/clients/AwsClient.py

We need to differentiate the snapshots/backups created by SF, from self triggered backups during
major version upgrade.
This also helps in identifying the snapshots based on 'description' during cleaning up.

Make description for snapshot parameterizable

---

lib/clients/AzureClient.py
requirements.txt

Description:
Bumping the version of Azure mgmt compute library and passing zone
parameter while creating disk for restore

Fixes #28: Backup & Restore fails for Azure with introduction of Availability Zone

---

lib/clients/AzureClient.py

Requirement : If temp_volume size is retreived from snapshot_size instead of instance_size, then create-volume fails for azure. Reason: "none" returned for instance location"
Thus, adding a method, to get location

adding method to get instance location

---

lib/clients/AwsClient.py

* In order to reduce restore time, the disk type of  temporary disk (created from snapshot) has to be modified to type 'gp2'
* We have parametrised volume type, so that services can specify required type. Default is standard.
* Reg. cost issue, approval is sent in mail.

Improve RTO on AWS

---

lib/clients/AzureClient.py
lib/clients/GcpClient.py
tests/test_clients_GcpClient.py

Some of the attribs from credentials object were not being set during GcpClient and AzureClient creation. This is being fixed as part of this PR.

Fix GCP / Azure backup failures as part credhub integration

---

lib/clients/AwsClient.py
tests/test_clients_AwsClient.py

* Before attachment is created between volume and instance in AwsClient, it is required to populate volume-device mappings, as a free device for attachment is determined based on these mappings.
* Hence added a method to refresh this mapping and a call to this method before attachment creation starts.

Added method to refresh devices list before creating attachment

---

lib/clients/BaseClient.py

* To reduce the frequency at which iaas is polled to know the status of operation default value of 'poll_delay_time' is increased.

increased default poll_delay_time value

---

lib/clients/AzureClient.py

With blob-ops operation, there won't be an `instance-id` config parameter in the function invocation. However, for Azure IaaS client, one action (getting availability zone) was happening for blob-ops, thus failing in the process. This PR should fix the bug.

Fixing a bug in the Azure client

---

lib/clients/AwsClient.py

* This PR adds retry configuration while creation of s3 client and resource. 
* This step is taken towards ensuring more and more resiliency in the library as it gets used in high load scenarios, thus also inviting many new exceptions such RequestLimitExceededException.
* To implement this, a config parameter provided by SDK is used. See:
[1] https://boto3.readthedocs.io/en/latest/reference/core/session.html#boto3.session.Session.resource
[2] https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html

[Backup Improvements] retries for s3 resource and client

---

lib/clients/GcpClient.py
requirements.txt
tests/test_clients_GcpClient.py

The snapshot creation time is returned in RFC3339 format for GCP IaaS.
In this PR, we are modifying the logic to first convert it to UTC format and then return the value.

Converting the snapshot creation timestamp to UTC for GCP IaaS

---

lib/clients/OpenstackClient.py

* It has been pointed out that description of exceptions occurred during interactions with infra could be useful for later debugging. Hence adding some missing logging statements during exception handling in OpenStackClient.
* Related BL (HCPCFS-1647).

Adding logging statements for exception scenarios in OpenStackClient

---

.travis.yml
lib/clients/AliClient.py
lib/config.py
requirements.txt
tests/data/ali/bucket.put.nosuchbucket.json
tests/test_clients_AliClient.py

This PR introduces the `AliClient` to the backup-restore library.
This client will be needed to support any backup/restore operations in an `Ali` IaaS.
For now, this client introduces 3 functions: `getContainer`, `_upload_to_blobstore` and `_download_from_blobstore`. 
This will enable taking backups and storing in Object Storage and downloading these objects from ObjectStorage during restore.
This being an iterative change, the snapshot based functions will be introduced later.

Introduction of AliClient to the BnR lib

---

lib/clients/AliClient.py

Earlier, `download_to_blobstore` function contained `get_object` function, that downloaded the object and was meant to be read/stored in a variable. However, the requirement here is to download the blob to a local target (file).
Hence, using the `get_object_to_file` function which fixes the bug in `download_to_blobstore` function.

Fixing download of blobs operation for Ali IaaS

---

lib/config.py
tests/test_clients_GcpClient.py
tests/test_clients_OpenstackClient.py
tests/test_config.py
tests/utils/setup_constants.py

* Currently logs and other state of the previous backup/restore operation is cleared as part of create_iaas_client operation. However if operation fails before/within create_iaas_client, previous state and logs will still be present and hence external agent will conclude wrong result.
* This PR solves this problem by including this removal of logs in the very first call to library, i.e., inside parse_options operation.
* Apart from this, config.py is refactored for the ease of unit testing and readability. UTs for config.py are also added
* Duplicate of #51 .

Exposing new function to clear state (logs and last op) of previous operation

---

lib/clients/OpenstackClient.py

When OpenStack VMs are running inside the VMware hypervisors, the uuid detection doesn't work, because symlinks for VMware devices are made without hyphens, e.g.:
```sh
$ ls /dev/disk/by-id/ | grep 6b81837496cd4b8f8bc470dd4c34d5a2
wwn-0x6b81837496cd4b8f8bc470dd4c34d5a2
```
corresponds to the `6b818374-96cd-4b8f-8bc4-70dd4c34d5a2` cinder volume ID.
The suggested fix resolves disk detection.

Fix VMware volume detection

---

lib/clients/BaseClient.py
lib/clients/GcpClient.py
tests/test_clients_GcpClient.py

In this PR
* `retry` mechanism defined in `BaseClient` made usable to subclasses.
* Retries have been added in `get_container` operation

Adding retries in get_container operation in GcpClient

---

lib/clients/AliClient.py
lib/clients/AwsClient.py
lib/clients/AzureClient.py
lib/clients/GcpClient.py
tests/test_clients_AliClient.py
tests/test_clients_GcpClient.py

* In case of delete operations, the scenario when the object is not found on IaaS providers can be ignored.
* Added this modification for `aws` , `ali`, `azure` and  `gcp`

Added 404 handling in delete opeartions for alicloud, aws, gcp and azure

---

README.md
lib/clients/BaseClient.py
lib/config.py
tests/test_clients_AliClient.py
tests/test_clients_AwsClient.py
tests/test_clients_GcpClient.py
tests/test_clients_OpenstackClient.py
tests/test_config.py

This pull request adds a new mandatory command line parameter `--trigger` to backup operation.  The trigger parameter expects value as `on-demand` or `scheduled`. The cron jobs are expected to pass the arguments as `scheduled`.
The argument of `--trigger` parameter is then passed as a tag of the backup snapshot. Use `--trigger`  as `on-demand` by default.

Adding trigger method tag to the snapshots
